### ISSUE TITLE
Game crashes after startup

### ISSUE THREAD

**Issue by JammaTheHutt** [CraftedMods/nei-lotr#65]
#### Minecraft: ####
- NEI LOTR version: 1.0.0 BETA
- MinecraftForge version: 1.7.10
- LOTR Mod version: 36.11
- CodeChickenCore version: 1.0.7.48-universal
- NEI version: 1.0.5.120-universal
- Optifine and/or Fastcraft installed: Fastcraft 1.25
#### Java: #####
- Java version: 
- Allocated memory: 
- Are any other special JVM flags set: 
#### Operating System: ####
- Operating System:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 6/12/21 1:14 AM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: craftedMods/recipes/provider/NEIIntegrationManager
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: craftedMods/recipes/provider/NEIIntegrationManager
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at cpw.mods.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:317)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:505)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 5 more
Caused by: java.lang.ClassNotFoundException: craftedMods.recipes.provider.NEIIntegrationManager
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 32 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/IResourceManagerReloadListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 34 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.IResourceManagerReloadListener
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 38 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 5.4.0-65-generic
	Java Version: 1.8.0_282, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 889541568 bytes (848 MB) / 1171783680 bytes (1117 MB) up to 1771044864 bytes (1689 MB)
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=200M -Xmx1900M -Xms950M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge.jar) 
	UC	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UC	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UC	lotr{Update v36.11 for Minecraft 1.7.10} [The Lord of the Rings Mod] (LOTRMod v36.11.jar) 
	UE	neirecipehandlers{1.1.0-BETA} [NEI Recipe Handlers] (neiRecipeHandlers-1.1.0-BETA.jar) 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by CraftedMods** [comment]
NEI LOTR/NEI Recipe Handlers don't run on the dedicated server - they're client-only.

**Comment by JammaTheHutt** [comment]
Does that mean we can still use the nei lotr/handlers on our clients without having it in our server?

**Comment by CraftedMods** [comment]
Yes

**Comment by JammaTheHutt** [comment]
Alright will get back to you. Thanks!

**Comment by bartfartlord** [comment]
My single player world works fine, i have a server where me and a friend play on. We have played the server for awhile then out of the blue it stopped working. I spawn in the regular Minecraft world but when I try and make the gold ring it crashes me out any ideas why it happens? Could it be that I need to delete the NEI mods? Thank you

**Comment by MggMuggins** [comment]
Are the NEI mods running on your server? None of them should be necessary, you should be able to remove them. That's definitely a server issue, but probably out of scope for this issue tracker.

**Comment by CraftedMods** [comment]
Closed because of no responses.
